require('dotenv').config();
const mongoose = require('mongoose');
const Suburb = require('./models/Suburb');

const suburbs = [
  {suburb: "Alex Park - Part", code: "H1", Latitude: -17.7852, Longitude: 31.0391},
  {suburb: "Glen Norah", code: "H16", Latitude: -17.9002, Longitude: 30.9956},
  {suburb: "Mabvuku", code: "H15", Latitude: -17.8369, Longitude: 31.1571},
  {suburb: "Alex Park - Part", code: "H7", Latitude: -17.7852, Longitude: 31.0391},
  {suburb: "Glen Norah A - Part", code: "H19", Latitude: -17.9002, Longitude: 30.9956},
  {suburb: "Machipisa", code: "H29", Latitude: -17.9055, Longitude: 30.9754},
  {suburb: "Amalinda", code: "H16", Latitude: -17.9130, Longitude: 31.0702},
  {suburb: "Glen Wood", code: "H28", Latitude: -17.9085, Longitude: 30.9966},
  {suburb: "Malvern", code: "H17", Latitude: -17.7940, Longitude: 31.0678},
  {suburb: "Amalinda Farm", code: "H16", Latitude: -17.9130, Longitude: 31.0702},
  {suburb: "Glenview", code: "H16", Latitude: -17.9082, Longitude: 30.9763},
  {suburb: "Mandalay Park", code: "H14", Latitude: -17.8780, Longitude: 30.9985},
  {suburb: "Ambleside", code: "H4", Latitude: -17.7965, Longitude: 31.0503},
  {suburb: "Glenview - Part", code: "H23", Latitude: -17.9082, Longitude: 30.9763},
  {suburb: "Mandara", code: "H6", Latitude: -17.7805, Longitude: 31.1217},
  {suburb: "Amby", code: "H5", Latitude: -17.8012, Longitude: 31.1162},
  {suburb: "Greendale - Part", code: "H5", Latitude: -17.8012, Longitude: 31.1162},
  {suburb: "Marimba Park", code: "H4", Latitude: -17.8780, Longitude: 30.9856},
  {suburb: "Arbour Cres", code: "H16", Latitude: -17.7900, Longitude: 31.0865},
  {suburb: "Greendale - Part", code: "H6", Latitude: -17.7981, Longitude: 31.1174},
  {suburb: "Marlborough, Bluffhill", code: "H12", Latitude: -17.7606, Longitude: 31.0138},
  {suburb: "Art Farm", code: "H2", Latitude: -17.8087, Longitude: 31.1448},
  {suburb: "Greendale - Part", code: "H8", Latitude: -17.8012, Longitude: 31.1162},
  {suburb: "Mayfield Park", code: "H1", Latitude: -17.7855, Longitude: 31.0847},
  {suburb: "Ashbritle", code: "H2", Latitude: -17.8100, Longitude: 31.0057},
  {suburb: "Greendcroft", code: "H12", Latitude: -17.7811, Longitude: 31.0217},
  {suburb: "Mbare", code: "H9", Latitude: -17.8655, Longitude: 31.0175},
  {suburb: "Ashdown Park, Bloomingdale", code: "H13", Latitude: -17.7964, Longitude: 31.0181},
  {suburb: "Greengrove", code: "H6", Latitude: -17.7845, Longitude: 31.1248},
  {suburb: "Merwede", code: "H11", Latitude: -17.7933, Longitude: 31.0435},
  {suburb: "Athlone", code: "H5", Latitude: -17.8056, Longitude: 31.1064},
  {suburb: "Greystone Park", code: "H7", Latitude: -17.7461, Longitude: 31.1321},
  {suburb: "Meyrick Park", code: "H13", Latitude: -17.7875, Longitude: 31.0178},
  {suburb: "Athlone - Part", code: "H6", Latitude: -17.8056, Longitude: 31.1064},
  {suburb: "Grobbie Park", code: "H17", Latitude: -17.8234, Longitude: 31.0590},
  {suburb: "Midlands", code: "H17", Latitude: -17.8242, Longitude: 31.0581},
  {suburb: "Avenues", code: "H22", Latitude: -17.8267, Longitude: 31.0369},
  {suburb: "Groombridge", code: "H2", Latitude: -17.7762, Longitude: 31.1044},
  {suburb: "Milton Park", code: "H13", Latitude: -17.7942, Longitude: 31.0472},
  {suburb: "Avondale", code: "H1", Latitude: -17.7598, Longitude: 31.0591},
  {suburb: "Guildform Estate", code: "H7", Latitude: -17.7753, Longitude: 31.1021},
  {suburb: "Monavale", code: "H1", Latitude: -17.7696, Longitude: 31.0383},
  {suburb: "Avondale West", code: "H1", Latitude: -17.7755, Longitude: 31.0442},
  {suburb: "Gunhil", code: "H7", Latitude: -17.7981, Longitude: 31.0771},
  {suburb: "Msasa Park", code: "H14", Latitude: -17.8251, Longitude: 31.1023},
  {suburb: "Avonlea - Part", code: "H1", Latitude: -17.7613, Longitude: 31.0438},
  {suburb: "Haig Park", code: "H13", Latitude: -17.8021, Longitude: 31.0309},
  {suburb: "Mt Pleasant & Heights", code: "H2", Latitude: -17.7729, Longitude: 31.0751},
  {suburb: "Avonlea West", code: "H12", Latitude: -17.7732, Longitude: 31.0408},
  {suburb: "Harare Rd W", code: "H16", Latitude: -17.7851, Longitude: 31.0437},
  {suburb: "Mt Hampden", code: "H3", Latitude: -17.7713, Longitude: 30.9996},
  {suburb: "Ballantyne Park", code: "H7", Latitude: -17.7727, Longitude: 31.0564},
  {suburb: "Harava Dam", code: "H17", Latitude: -17.8104, Longitude: 31.0106},
  {suburb: "Matidoda", code: "H13", Latitude: -17.8022, Longitude: 31.0399},
  {suburb: "Bannockbum", code: "H2", Latitude: -17.7801, Longitude: 31.0661},
  {suburb: "Hatcliffe", code: "H7", Latitude: -17.8194, Longitude: 31.0345},
  {suburb: "Mufakose", code: "H24", Latitude: -17.8971, Longitude: 30.9936},
  {suburb: "Barrington Rd suburb", code: "H16", Latitude: -17.8282, Longitude: 31.0421},
  {suburb: "Hatfield West", code: "H10", Latitude: -17.8845, Longitude: 31.0227},
  {suburb: "Mutare Rd", code: "H15", Latitude: -17.8274, Longitude: 31.0349},
  {suburb: "Budiriro", code: "H23", Latitude: -17.9813, Longitude: 31.0645},
  {suburb: "Waterfalls", code: "H17", Latitude: -17.9149, Longitude: 31.0466},
  {suburb: "Westlea", code: "H13", Latitude: -17.8168, Longitude: 31.0362},
  {suburb: "Westwood", code: "H18", Latitude: -17.7913, Longitude: 31.0146},
  {suburb: "Widdecombe", code: "H14", Latitude: -17.8194, Longitude: 31.0082},
  {suburb: "Wilmington Park", code: "H14", Latitude: -17.8433, Longitude: 31.0839},
  {suburb: "Winchdon", code: "H7", Latitude: -17.7719, Longitude: 31.0861},
  {suburb: "Ushewekunze & Southlea Park", code: "H16", Latitude: -17.9341, Longitude: 31.0877},
  {suburb: "Rydale Ridge", code: "H24", Latitude: -17.9487, Longitude: 31.0822},
  {suburb: "Whitecliffe", code: "H24", Latitude: -17.9399, Longitude: 31.0631},
  {suburb: "Industrial suburbs", code: "H35", Latitude: -17.9479, Longitude: 31.0513},
  {suburb: "Msasa", code: "H30", Latitude: -17.7964, Longitude: 31.0999},
  {suburb: "Sunway City", code: "H30", Latitude: -17.8018, Longitude: 31.0915},
  {suburb: "Manresa", code: "H30", Latitude: -17.8212, Longitude: 31.1051},
  {suburb: "Graniteside", code: "H31", Latitude: -17.8604, Longitude: 31.0462},
  {suburb: "Ruwa", code: "H32", Latitude: -17.8900, Longitude: 31.2140},
  {suburb: "Workington", code: "H33", Latitude: -17.9572, Longitude: 31.0353},
  {suburb: "Willowvale", code: "H34", Latitude: -17.9474, Longitude: 30.9741},
  {suburb: "Southerton", code: "H35", Latitude: -17.9217, Longitude: 31.0186},
  {suburb: "Chitungwiza", code: "C1", Latitude: -18.0096, Longitude: 31.0795},
  {suburb: "Zengeza 1, 2, 3, 4 & 5", code: "C1", Latitude: -18.0143, Longitude: 31.0965},
  {suburb: "Seke Unit A, B, C, D, E", code: "C2", Latitude: -18.0227, Longitude: 31.0361},
  {suburb: "Seke Unit B, Makoni", code: "C3", Latitude: -18.0186, Longitude: 31.0354},
  {suburb: "GDC", code: "C4", Latitude: -17.9825, Longitude: 31.0417},
  {suburb: "Pumula South, Old Pumula, Pumula North, Pumula East, New Magwegwe, Magwegwe West, Magwegwe North, Gwabalanda (Dollar House suburb)", code: "B11", Latitude: -20.1975, Longitude: 28.5908},
  {suburb: "Nketa 9, Nketa 6, Nketa 8, Emganwini West", code: "B21", Latitude: -20.1972, Longitude: 28.5522},
  {suburb: "Westbury Rd, Monarch Steel, Thorn Grove, Consolidated Textiles, Zimplow, Connollys, Busmetals, National Foods, Turnal Asbestos, Nguboyenja, Umguza, Shiloh, Nyamandlovu", code: "B22", Latitude: -20.1151, Longitude: 28.5874},
  {suburb: "Cecil hotel, Kensington flats, Matopos Investments, Federal Courts, Trewithin flats, Castle crt, Athlone Mansions, Burlington Crt, Rogean Flats, City Centre East", code: "B23", Latitude: -20.1415, Longitude: 28.5917},
  {suburb: "Four Winds, Bumside (Chattie Rd), Hillside South, Eloana, Tshabalala Game Park, Hillside (Chipping Way),Fortunesgate, Relay Stn, Burnside, Douglasdale, Waterford, Burnside, Plumtree, Dingimuzi, Thekwane, Empandeni, Fig tree, Tsholotsho, Solusi, Matopos Research Station, Matopo National Park", code: "B31", Latitude: -20.2222, Longitude: 28.5903},
  {suburb: "Emakhandeni, Njube, Njube, New & West Lobengula, Luveve, Gwabalanda, Old Lobengula, Mzilikazi, Barbourfields", code: "B32", Latitude: -20.1581, Longitude: 28.5993},
  {suburb: "South World, Montrose, Barham Green, Bellevue, Newton West, West Somerton", code: "B33", Latitude: -20.1766, Longitude: 28.5852},
  {suburb: "Donnington Industrial suburb, colcom, BMA, Radar Industries, Dunlop, Edgars industrial park, Donnington West", code: "B34", Latitude: -20.1834, Longitude: 28.6179},
  {suburb: "Entumbane, Nhliziyo Shops, Cowdray Park, Hellenvale, Luveve Siding, The Jungle, Highmount, United College, Harrisvale, Umgusa, Aisebley, North Trenance, Umvitshwa Abattoirs, Norwood, Richmond, State house, Lobenvale", code: "B41", Latitude: -20.1974, Longitude: 28.5942},
  {suburb: "Nkulumane1, 11, GMB, Kelvin West, Sizinda, Nkulumane Complex", code: "B42", Latitude: -20.1859, Longitude: 28.5743},
  {suburb: "Turk, Turk Mine, Marry Elen,Dramer, Queens mine, Mthonyeni, Motapa, St Lukes", code: "B43", Latitude: -20.2342, Longitude: 28.5679},
  {suburb: "Hamilton School, Greenhill, Montrose, Hillcrest, Hillside shopping Centre, Malindela", code: "B51", Latitude: -20.1921, Longitude: 28.5794},
  {suburb: "Famona, Fire Station, ZITF, Zonke Izizwe Shops, Bradfields, Hillside, Leander Ave, Windermere Rd, Bellevue, Newton West, Cecil Ave, Hillside School, Morningside, Hillside West", code: "B52", Latitude: -20.1821, Longitude: 28.5801},
  {suburb: "Wet Blue, Art Printers, Paltes, Falcon St, Datlabs, Nimr and Chapman, New CSC, Bakeshire, Premier Electric, Alloy Die Cast, Cotton Printers, Halifax rd, Suppercanners, Zimbabwe Tannery, Kerries Engineering, Engutsheni Mental Hospital, Old Farmers Co-op, Arenel, Directory publishers, Lobels", code: "B53", Latitude: -20.1752, Longitude: 28.5789},
  {suburb: "Queens park west, Tegela, Sunnyside, P/hurst, Queens park east, Brcc, Marvel compound, N/end, Park nursery, Crematorium, Kenilworth, SOS Children's Village, Nortlea sch, Heath field cres, PTC Exchange, Enfield Rd SS, Acacia, Merton", code: "B54", Latitude: -20.1641, Longitude: 28.5989},
  {suburb: "Beech Ave, Jaranda Ave, Matabele Steam, Blasson Av; Mattheyson Rd, Rowena, Umguza, Newmansford, Kingsdale, Mahatshula", code: "B55", Latitude: -20.1422, Longitude: 28.5931},
  {suburb: "West Commonage, Msitheli Sch, Mpopoma High, Matshobane, Woodville, Clay Products, Montgommery, Fairstar, Fairbridge Police", code: "B61", Latitude: -20.1445, Longitude: 28.5776},
  {suburb: "Nkulumane 1, Nkulumane 11, Nkulumane 14, Nkulumane 12, Nkulumane 15, Tshabalala Ext, Nkulumane Zesa Offices, Nketa 7", code: "B62", Latitude: -20.1792, Longitude: 28.6043},
  {suburb: "Davies Granite, Bulawayo Bottlers, Khami Rd West, Kelvin SS, Kelvin West Industry, Byo Jobbing, Machipisa, Golden, Kelvin North, Radar, BMA, Colcom, West commonage Police", code: "B63", Latitude: -20.1463, Longitude: 28.5754},
  {suburb: "Khumalo suburb, Killaney, Nust, Old Nic Mine, Glengarry, Mahatshula South, Parklands, School of Mines, Ascot shopping centre, Brady Barracks, Elangeni Training Centre, Netherby Rd Paddonhurst, Surburbs, Holiday Inn", code: "B71", Latitude: -20.1697, Longitude: 28.5928},
  {suburb: "Riverside, MacDonalds Bricks, Kensington, Sunninghill, Matsheumhlope, Lochview, Riverside south, Gumtree, Manningdale, Wilsgrove, Selbourne Park, Baxendale", code: "B72", Latitude: -20.1507, Longitude: 28.5946},
  {suburb: "Hillside East, Matsheumhlope, Fortunesgate, Selbourne Park, Ilanda, Milton Jnr, Woodlands, Waterford", code: "B73", Latitude: -20.1564, Longitude: 28.5799},
  {suburb: "Belmont suburb, Bristol rd, Stoke st, 12 - 15 Ave, CABS, Milton Jnr", code: "B74", Latitude: -20.1669, Longitude: 28.5742},
  {suburb: 'Plumtree', code: 'PLM1', Latitude: -20.4830, Longitude: 27.8119},
  {suburb: 'Filabusi', code: 'FIL', Latitude: -20.5417, Longitude: 29.2877},
  {suburb: 'Turk, Motapa, Queens', code: 'TRK1', Latitude: -20.2333, Longitude: 28.9333},
  {suburb: 'EsIgodin', code: 'ESG', Latitude: -20.2833, Longitude: 28.9333},
  {suburb: 'MAKAKAVHULE, TEL ONE MASASANE, BENFER, CUNIFFER, BISHOPSTONE, BK CAREWOOD, VALLEY JUICE, ZHOVE INCUDING CHIEF SITAUDZE, MAZUNGA SAFARIS, TAULA AND BEITBRIDGE CBD. DAM ZINWA, MASERA IRRIGATION, KWALU IRRIGATION, MINISTER MOHADI FARM, CHANANGANA, ZEZANI', code: 'BB1', Latitude: -22.2167, Longitude: 30.0000},
  {suburb: 'BEITBRIDGE CBD, BOARDER SERVICE STATION, HILLCLOSE, IMPAL DRIVE, BAOBAB, LONDA HOTEL, ZESA COMPLEX, SPAR, CBZ, ZRP MEDIUM DENSITY, PETERS MOTEL, BEITBRIDGE INN, DAWN LIGHT BAKERY, BEITBRIDGE INDUSTRIAL & ADJACENT suburbS, ARCACIA, GMB, NOCZIM, TOTAL SERVICE STATION, SAS FUEL, BP SERVICE STATION, RED QUEEN, ZALAWI MEDIUM, DENSITY, DULIBADZIMU T/SHIP UP TO MASHAVIRE B/C, HOLIDAY INN, LIMPOMPO LODGE, ONE INDEPENDENT ARMY CAMP, CHICAGO, LUTUMBA, TONGWE, CHAFUCHE, CHASVINGO UPTO AND INCLUDING CHIEF MATHIBE, TEL ONE REPEATER STN MATHAMVE, MATSHILONI, CAREWOOD, LESANTH suburb, BUBI VILLAGE, LION AND ELEPHANT HOTEL, INCUDING ALL NRZ SIDINGS, DULIBADZIMU LIGHT INDUSTRIAL, DULIBADZIMU T/SHIP, CHINEMBIRI S/S INCLUDING BAMBAZONKE AND LONG DISTANCE RANK, HOSPITAL UP TO AND INCLUDING MASHAKADA B/C, LIMPOMPO VIEW, SHULE SHULE B/C, QUICK SPAR, IMMIGRATION SHUMBA BLOCK.', code: 'BB', Latitude: -22.2167, Longitude: 30.0000},
  {suburb: 'RIVER RANCH MINE, NOTTINGHAM ESTATES, TULI COAL MINE, SENTINEL RANCH, SHASHE B/C AND IRRIGATION, JALUKANGA IRRIGATION, BILI IRRIGATION.', code: 'BB', Latitude: -22.2167, Longitude: 30.0000},
  {suburb: 'GWANDA CBD, JAUNDA T/SHIP, ZRP, PAs OFFICE, MTSHAZO BC, MTSHABEZI MISSION, MTSHABEZI SEC SCHOOL, MTSHABEZI PRIMARY SCHOOL, STANMORE B/C, INFINDI RANSCH, LOUNGE BILLE, BLANKET FARM, MPOENGS BORDER POST, MAPHISA, MAKWE, TULI, VALLEY IRRIGATION, KEZI, BRUNAPERG, TSHELANYEMBA HOSPITAL, INGWIZI, SENONDO, BAR 20, MTSHABEZI PUMPS, FREDA MINE, HORN MINE', code: 'GW1', Latitude: -20.9333, Longitude: 29.0000},
  {suburb: 'PPC COLLEEN BAWN', code: 'GW', Latitude: -20.4833, Longitude: 28.7167},
  {suburb: 'MAMBO KING, BLANKET MINE, VUBACHIKWE MINE, GG MINE, CLBURG MINE, BINA 21 MINE, MALAYALAM MINE, PERIGREEN', code: 'GW3', Latitude: -20.2500, Longitude: 28.5833},
  {suburb: 'MANAMA MISSION, MANAMA SEC SCHOOL, KAFUSI SEC SCHOOL, KAFUSI BC, HWALI BC, HWALI PR, HWALI SEC SCH, FUMUKWE BC, BETHEL BC, GARANYEMBA BC, GARANYEMBA PR, SEC S, TELONE GARANYEMBA, TELONE MANAMA, BETHEN SEC + PRI, BUVUMA PR + SEC SCH, BUVUMA BC, MBETA MINE, MANDIWONGOLA BC, GUNGWE BC, GUNGWE SEC, CHIEF MATHE, PEVEVE BC, SAMLODI BC, SAMLODI PR, TIBELI, BC, SILONGA BC, SILONGA PR + SEC, NTALALE, BC, NTALALE PR + SEC, ZINWA NTALALE, WEST NICHOLSON B/C & SURROUNDING suburbS, COLLEEN BAWN, TODDS', code: 'GW4', Latitude: -21.2167, Longitude: 29.0000},
  {suburb: 'Mandava, Makwasha, Highlands, Siboza, Mabasa, Denge, Takavarasha', code: 'ZV', Latitude: -19.0833, Longitude: 30.8667},
  {suburb: 'Mine Shaft, Nil, Kandondo, Maglas, Hillview, Noevale', code: 'ZV2', Latitude: -20.6000, Longitude: 29.9167},
  {suburb: 'Mberengwa, Mataga , Mnene, Mabika, Phoenix, C Mine, Mberengwa centre', code: 'ZV3', Latitude: -21.7833, Longitude: 29.9667},
  { suburb: 'Eastlea', code: 'ZV4', Longitude: '29.8172', Latitude: '-19.4596' },
  { suburb: 'Shushine', code: 'ZV4', Longitude: '29.8126', Latitude: '-19.4574' },
  { suburb: 'Zvizvobgo', code: 'ZV4', Longitude: '29.8099', Latitude: '-19.4528' },
  { suburb: 'Behans plots', code: 'ZV4', Longitude: '29.8057', Latitude: '-19.4535' },
  { suburb: 'Sabi vlei', code: 'ZV4', Longitude: '29.8051', Latitude: '-19.4576' },
  { suburb: 'Vugwi', code: 'ZV4', Longitude: '29.8049', Latitude: '-19.4634' },
  { suburb: 'Zeederburg', code: 'ZV4', Longitude: '29.8064', Latitude: '-19.4691' },
  { suburb: 'Ascot', code: 'G1', Longitude: '29.8406', Latitude: '-19.4431' },
  { suburb: 'Brakenhurst', code: 'G1', Longitude: '29.8299', Latitude: '-19.4617' },
  { suburb: 'Nashville', code: 'G1', Longitude: '29.8172', Latitude: '-19.4602' },
  { suburb: 'Nothlea', code: 'G1', Longitude: '29.8176', Latitude: '-19.4566' },
  { suburb: 'Regina Mundi', code: 'G1', Longitude: '29.8225', Latitude: '-19.4617' },
  { suburb: 'Montrose', code: 'G1', Longitude: '29.8219', Latitude: '-19.4441' },
  { suburb: 'Clonsila', code: 'G1', Longitude: '29.8256', Latitude: '-19.4561' },
  { suburb: 'MCC', code: 'G1', Longitude: '29.8283', Latitude: '-19.4429' },
  { suburb: 'Athlone', code: 'G1', Longitude: '29.8261', Latitude: '-19.4499' },
  { suburb: 'Village Lodge', code: 'G1', Longitude: '29.8329', Latitude: '-19.4579' },
  { suburb: 'Mtapa', code: 'G1', Longitude: '29.8342', Latitude: '-19.4543' },
  { suburb: 'Msungwe block', code: 'G1', Longitude: '29.8391', Latitude: '-19.4626' },
  { suburb: 'Ridgemond', code: 'G1', Longitude: '29.8405', Latitude: '-19.4494' },
  { suburb: 'Hwahwa', code: 'G1', Longitude: '29.8439', Latitude: '-19.4432' },
  { suburb: 'Indiva farms', code: 'G1', Longitude: '29.8373', Latitude: '-19.4422' },
  { suburb: 'Dailsford', code: 'G1', Longitude: '29.8415', Latitude: '-19.4483' },
  { suburb: 'Surprise', code: 'G1', Longitude: '29.8358', Latitude: '-19.4464' },
  { suburb: 'ZBC transmitter', code: 'G1', Longitude: '29.8301', Latitude: '-19.4484' },
  { suburb: 'Chiundura', code: 'G1', Longitude: '29.8189', Latitude: '-19.4519' },
  { suburb: 'Gune Fowl', code: 'G1', Longitude: '29.8261', Latitude: '-19.4439' },
  { suburb: 'Senga', code: 'G2', Longitude: '', Latitude: '' },
  { suburb: 'Makusha', code: 'G2', Longitude: '', Latitude: '' },
  { suburb: 'Nehosho', code: 'G2', Longitude: '', Latitude: '' },
  { suburb: 'ZB', code: 'G2', Longitude: '', Latitude: '' },
  { suburb: 'MSU', code: 'G2', Longitude: '19.4845', Latitude: '29.8353' },
  { suburb: 'Stone crushers', code: '', Longitude: '', Latitude: '' },
  { suburb: 'Lapanzi', code: 'G4', Longitude: '29.8171', Latitude: '-19.4652' },
  { suburb: 'Fairfields', code: 'G4', Longitude: '29.8053', Latitude: '-19.4624' },
  { suburb: 'Chivu town', code: 'G5', Longitude: '29.8028', Latitude: '-19.4499' },
  { suburb: 'Daramombe', code: 'G5', Longitude: '29.8007', Latitude: '-19.4554' },
  { suburb: 'Gutu', code: 'G6', Longitude: '29.7974', Latitude: '-19.4696' },
  { suburb: 'Athens', code: 'G6', Longitude: '', Latitude: '' },
  { suburb: 'XIN YU', code: 'G8', Longitude: '', Latitude: '' },
  { suburb: 'Southview', code: 'G8', Longitude: '', Latitude: '' },
  { suburb: 'Ivene', code: 'G8', Longitude: '', Latitude: '' },
  { suburb: 'CMED', code: 'G8', Longitude: '', Latitude: '' },
  { suburb: 'Vaka africa', code: 'G8', Longitude: '', Latitude: '' },
  { suburb: 'Lapanzi', code: 'G4', Longitude: '29.8171', Latitude: '-19.4652' },
{ suburb: 'Fairfields', code: 'G4', Longitude: '29.8053', Latitude: '-19.4624' },
{ suburb: 'Mvuma town', code: 'G4', Longitude: '', Latitude: '' },
{ suburb: 'Central Estates', code: 'G4', Longitude: '', Latitude: '' },
{ suburb: 'Mushayabvudzi', code: 'G4', Longitude: '', Latitude: '' },
{ suburb: 'Chivu town', code: 'G5', Longitude: '29.8028', Latitude: '-19.4499' },
{ suburb: 'Daramombe', code: 'G5', Longitude: '29.8007', Latitude: '-19.4554' },
{ suburb: 'Chivu farms', code: 'G5', Longitude: '', Latitude: '' },
{ suburb: 'Nharira', code: 'G5', Longitude: '', Latitude: '' },
{ suburb: 'Zada', code: 'G5', Longitude: '', Latitude: '' },
{ suburb: 'Ortonsdrift', code: 'G5', Longitude: '', Latitude: '' },
{ suburb: 'St Francis of Asis', code:'G5', Longitude: '', Latitude: '' },
{ suburb: 'Gutu', code: 'G6', Longitude: '30.2715', Latitude: '-19.6675' },
{ suburb: 'Chaka', code: 'G6', Longitude: '', Latitude: '' },
{ suburb: 'Felixburg Farms', code: 'G6', Longitude: '', Latitude: '' },
{ suburb: 'Drifontein', code: 'G6', Longitude: '', Latitude: '' },
{ suburb: 'HollyCross', code: 'G6', Longitude: '', Latitude: '' },
{ suburb: 'Torwood', code: 'K16', Longitude: '', Latitude: '' },
{ suburb: 'Swimming pool', code: 'K2', Longitude: '', Latitude: '' },
{ suburb: 'Brandford', code: 'K7 ☑', Longitude: '', Latitude: '' },
{ suburb: 'Chiundura road', code: 'K2', Longitude: '', Latitude: '' },
{ suburb: 'Kwekwe East Farms', code: 'K7', Longitude: '', Latitude: '' },
{ suburb: 'Fitchlea', code: 'K2', Longitude: '', Latitude: '' },
{ suburb: 'Bumbe', code: 'K7 ☑', Longitude: '', Latitude: '' },
{ suburb: 'Chicago', code: 'K2', Longitude: '', Latitude: '' },
{ suburb: 'Ngezi National Park', code: 'K7 ☑', Longitude: '', Latitude: '' },
{ suburb: 'Gaika', code: 'K2', Longitude: '', Latitude: '' },
{ suburb: 'Golden mile', code: 'K2', Longitude: '', Latitude: '' },
{ suburb: 'Amaveni', code: 'K8', Longitude: '', Latitude: '' },
{ suburb: 'Kwekwe Town CBD', code: 'K12', Longitude: '', Latitude: '' },
{ suburb: 'Maiguru', code: 'K8', Longitude: '', Latitude: '' },
{ suburb: 'OK Mart', code: 'K8', Longitude: '', Latitude: '' },
{ suburb: 'Trustford', code: 'K10', Longitude: '', Latitude: '' },
{ suburb: 'Metropeach', code: 'K8', Longitude: '', Latitude: '' },
{ suburb: 'Primrose', code: 'K10', Longitude: '', Latitude: '' },
{ suburb: 'N Richards', code: 'K8', Longitude: '', Latitude: '' },
{ suburb: 'Ivanhoe', code: 'K10', Longitude: '', Latitude: '' },
{ suburb: 'Simba', code: 'K10', Longitude: '', Latitude: '' },

{ suburb: "Surrey", code: "K10", Longitude: "", Latitude: "" },
{ suburb: "Mild engineering", code: "K10", Longitude: "", Latitude: "" },
{ suburb: "Sherwood block", code: "K4", Longitude: "", Latitude: "" },
{ suburb: "Truckers", code: "K11", Longitude: "", Latitude: "" },
{ suburb: "Indarama mine", code: "K4", Longitude: "", Latitude: "" },
{ suburb: "Moss mine", code: "K11", Longitude: "", Latitude: "" },
{ suburb: "Ming Chang Mine", code: "K4", Longitude: "", Latitude: "" },
{ suburb: "Grandsharp", code: "K11", Longitude: "", Latitude: "" },
{ suburb: "Sewerage works", code: "K11", Longitude: "", Latitude: "" },
{ suburb: "Caravan park", code: "K11", Longitude: "", Latitude: "" },
{ suburb: "Dyno Nobel", code: "K11", Longitude: "", Latitude: "" },
{ suburb: "Marivale", code: "K3", Longitude: "", Latitude: "" },
{ suburb: "Cricket Mine", code: "K3", Longitude: "", Latitude: "" },
{ suburb: "Maheu", code: "K3", Longitude: "", Latitude: "" },
{ suburb: "Summerset", code: "K3", Longitude: "", Latitude: "" },
{ suburb: "Battlefields police", code: "K3", Longitude: "", Latitude: "" },
{ suburb: "Sedan", code: "K3", Longitude: "", Latitude: "" },
{ suburb: "Brompton Mine", code: "K3", Longitude: "", Latitude: "" },
{ suburb: "ZNA Camp", code: "K3", Longitude: "", Latitude: "" },
{ suburb: "Lancashire steel", code: "K1", Longitude: "", Latitude: "" },
{ suburb: "Mbizo 1,3,4,9,10,19", code: "K5", Longitude: "", Latitude: "" },
{ suburb: "GMB", code: "K1", Longitude: "", Latitude: "" },
{ suburb: "Haggie Rand", code: "K1", Longitude: "", Latitude: "" },
{ suburb: "Dendairy", code: "K1", Longitude: "", Latitude: "" },
{ suburb: "Zupco", code: "K1", Longitude: "", Latitude: "" },
{ suburb: "Railway Station", code: "K1", Longitude: "", Latitude: "" },
{ suburb: "JIT", code: "K1", Longitude: "", Latitude: "" },
{ suburb: "Kwekwe polytechnic", code: "K1", Longitude: "", Latitude: "" },
{ suburb: "Oliken", code: "K1", Longitude: "", Latitude: "" },
{ suburb: "VID", code: "K1", Longitude: "", Latitude: "" },
{ suburb: "Msasa", code: "K1", Longitude: "", Latitude: "" },
{ suburb: "Southwood", code: "K1", Longitude: "", Latitude: "" },
{ suburb: "Golden Acres", code: "K1", Longitude: "", Latitude: "" },
{ suburb: "Mbizo2,5,6,4 shops, 11,16,17", code: "K6", Longitude: "", Latitude: "" },
{ suburb: "Mbizo 1,7,8,13,21", code: "K9", Longitude: "", Latitude: "" },
{ suburb: "Alex Park - Part", code: "H1", Longitude: "", Latitude: "" },
{ suburb: "Glen Norah", code: "H16", Longitude: "", Latitude: "" },
{ suburb: "Mabvuku", code: "H15", Longitude: "", Latitude: "" },
{ suburb: "Alex Park - Part", code: "H7", Longitude: "", Latitude: "" },
{ suburb: "Glen Norah A - Part", code: "H19", Longitude: "", Latitude: "" },
{ suburb: "Machipisa", code: "H29", Longitude: "", Latitude: "" },
{ suburb: "Amalinda", code: "H16", Longitude: "", Latitude: "" },
{ suburb: "Glen Wood", code: "H28", Longitude: "", Latitude: "" },
{ suburb: "Malvern", code: "H17", Longitude: "", Latitude: "" },
{ suburb: "Amalinda Farm", code: "H16", Longitude: "", Latitude: "" },
{ suburb: "Glenview", code: "H16", Longitude: "", Latitude: "" },
{ suburb: "Mandalay Park", code: "H14", Longitude: "", Latitude: "" },
{ suburb: "Ambleside", code: "H4", Longitude: "", Latitude: "" },
{ suburb: "Glenview - Part", code: "H23", Longitude: "", Latitude: "" },
{ suburb: "Mandara", code: "H6", Longitude: "", Latitude: "" },
{ suburb: "Amby", code: "H5", Longitude: "", Latitude: "" },
{ suburb: "Greendale - Part", code: "H5", Longitude: "", Latitude: "" },
{ suburb: "Marimba Park", code: "H4", Longitude: "", Latitude: "" },
{ suburb: "Arbour Cres", code: "H16", Longitude: "", Latitude: "" },
{ suburb: "Greendale - Part", code: "H6", Longitude: "", Latitude: "" },
{ suburb: "Marlborough, Bluffhill", code: "H12", Longitude: "", Latitude: "" },
{ suburb: "Art Farm", code: "H2", Longitude: "", Latitude: "" },
{ suburb: "Greendale - Part", code: "H8", Longitude: "", Latitude: "" },
{ suburb: "Mayfield Park", code: "H1", Longitude: "", Latitude: "" },
{ suburb: "Ashbritle", code: "H2", Longitude: "", Latitude: "" },
{ suburb: "Greendcroft", code: "H12", Longitude: "", Latitude: "" },
{ suburb: "Mbare", code: "H9", Longitude: "", Latitude: "" },
{ suburb: "Ashdown Park, Bloomingdale", code: "H13", Longitude: "", Latitude: "" },
{ suburb: "Greengrove", code: "H6", Longitude: "", Latitude: "" },
{ suburb: "Merwede", code: "H11", Longitude: "", Latitude: "" },
{ suburb: "Athlone", code: "H5", Longitude: "", Latitude: "" },
{ suburb: "Greystone Park", code: "H7", Longitude: "", Latitude: "" },
{ suburb: "Meyrick Park", code: "H13", Longitude: "", Latitude: "" },
{ suburb: "Athlone - Part", code: "H6", Longitude: "", Latitude: "" },
{ suburb: "Grobble Park", code: "H17", Longitude: "", Latitude: "" },
{ suburb: "Midlands", code: "H17", Longitude: "", Latitude: "" },
{ suburb: "Avenues", code: "H22", Longitude: "", Latitude: "" },
{ suburb: "Groombridge", code: "H2", Longitude: "", Latitude: "" },
{ suburb: "Milton Park", code: "H13", Longitude: "", Latitude: "" },
{ suburb: "Avondale", code: "H1", Longitude: "", Latitude: "" },
{ suburb: "Guildform Estate", code: "H7", Longitude: "", Latitude: "" },
{ suburb: "Monavale", code: "H1", Longitude: "", Latitude: "" },
{ suburb: "Avondale West", code: "H1", Longitude: "", Latitude: "" },
{ suburb: "Gunhil", code: "H7", Longitude: "", Latitude: "" },
{ suburb: "Msasa Park", code: "H14", Longitude: "", Latitude: "" },
{ suburb: "Avonlea - Part", code: "H1", Longitude: "", Latitude: "" },
{ suburb: "Haig Park", code: "H13", Longitude: "", Latitude: "" },
{ suburb: "Mt Pleasant & Heights", code: "H2", Longitude: "", Latitude: "" },
{ suburb: "Avonlea West", code: "H12", Longitude: "", Latitude: "" },
{ suburb: "Harare Rd W", code: "H16", Longitude: "", Latitude: "" },
{ suburb: "Mt Hampden", code: "H3", Longitude: "", Latitude: "" },
{ suburb: "Ballantyne Park", code: "H7", Longitude: "", Latitude: "" },
{ suburb: "Harava Dam", code: "H17", Longitude: "", Latitude: "" },
{ suburb: "Matidoda", code: "H13", Longitude: "", Latitude: "" },
{ suburb: "Bannockbum", code: "H2", Longitude: "", Latitude: "" },
{ suburb: "Hatcliffe", code: "H7", Longitude: "", Latitude: "" },
{ suburb: "Mufakose", code: "H24", Longitude: "", Latitude: "" },
{ suburb: "Barrington Rd Area", code: "H16", Longitude: "", Latitude: "" },
{ suburb: "Hatfield West", code: "H10", Longitude: "", Latitude: "" },
{ suburb: "Mutare Rd", code: "H15", Longitude: "", Latitude: "" },
{ suburb: "Sherwood Park - Part", code: "H12", Longitude: "", Latitude: "" },
{ suburb: "Somerby Area", code: "H21", Longitude: "", Latitude: "" },
{ suburb: "Spring Heights", code: "H28", Longitude: "", Latitude: "" },
{ suburb: "Stanbury Park", code: "H12", Longitude: "", Latitude: "" },
{ suburb: "Startmore Farm", code: "H16", Longitude: "", Latitude: "" },
{ suburb: "Stoneridge Rd", code: "H17", Longitude: "", Latitude: "" },
{ suburb: "Strathaven", code: "H1", Longitude: "", Latitude: "" },
{ suburb: "Sunridge", code: "H12", Longitude: "", Latitude: "" },
{ suburb: "Tafara", code: "H15", Longitude: "", Latitude: "" },
{ suburb: "The Grange", code: "H8", Longitude: "", Latitude: "" },
{ suburb: "Thornpark", code: "H2", Longitude: "", Latitude: "" },
{ suburb: "Twentydales Ext.", code: "H17", Longitude: "", Latitude: "" },
{ suburb: "Tynwald North", code: "H13", Longitude: "", Latitude: "" },
{ suburb: "Tynwald South", code: "H4", Longitude: "", Latitude: "" },
{ suburb: "Umwinsidale", code: "H28", Longitude: "", Latitude: "" },
{ suburb: "Uplands", code: "H17", Longitude: "", Latitude: "" },
{ suburb: "Upper Mt Hampden", code: "H12", Longitude: "", Latitude: "" },
{ suburb: "Upper Reaches Rd", code: "H11", Longitude: "", Latitude: "" },
{ suburb: "Vainona", code: "H7", Longitude: "", Latitude: "" },
{ suburb: "Bangala", code: "MASV01", Longitude: "", Latitude: "" },
{ suburb: "Bannockburn", code: "MASV02", Longitude: "", Latitude: "" },
{ suburb: "Bikita Minerals", code: "MASV03", Longitude: "", Latitude: "" },
{ suburb: "Bikita Village", code: "MASV04", Longitude: "", Latitude: "" },
{ suburb: "Birthday Mine", code: "MASV05", Longitude: "", Latitude: "" },
{ suburb: "BNR", code: "MASV06", Longitude: "", Latitude: "" },
{ suburb: "Buffalo Range", code: "MASV07", Longitude: "", Latitude: "" },
{ suburb: "Bushmead", code: "MASV08", Longitude: "", Latitude: "" },
{ suburb: "Checheche", code: "MASV09", Longitude: "", Latitude: "" },
{ suburb: "Chidza - Guni", code: "MASV10", Longitude: "", Latitude: "" },
{ suburb: "Chilonga", code: "MASV11", Longitude: "", Latitude: "" },
{ suburb: "Chiredzi South", code: "MASV12", Longitude: "", Latitude: "" },
{ suburb: "Chiredzi Town", code: "MASV13", Longitude: "", Latitude: "" },
{ suburb: "Chirumhanzu", code: "MASV14", Longitude: "", Latitude: "" },
{ suburb: "Chishamiso", code: "MASV15", Longitude: "", Latitude: "" },
{ suburb: "Chisumbanje", code: "MASV16", Longitude: "", Latitude: "" },
{ suburb: "Chivi", code: "MASV17", Longitude: "", Latitude: "" },
{ suburb: "CSC", code: "MASV18", Longitude: "", Latitude: "" },
{ suburb: "Chiwara", code: "MASV19", Longitude: "", Latitude: "" },
{ suburb: "College", code: "MASV20", Longitude: "", Latitude: "" },
{ suburb: "Dawlish Estate", code: "MASV21", Longitude: "", Latitude: "" },
{ suburb: "Dinhire", code: "MASV22", Longitude: "", Latitude: "" },
{ suburb: "Dzoro Area", code: "MASV23", Longitude: "", Latitude: "" },
{ suburb: "Eastvale", code: "MASV24", Longitude: "", Latitude: "" },
{ suburb: "Eagle Mont", code: "MASV25", Longitude: "", Latitude: "" },
{ suburb: "Esquilingwe", code: "MASV26", Longitude: "", Latitude: "" },
{ suburb: "Farmers Hall", code: "MASV27", Longitude: "", Latitude: "" },
{ suburb: "Gt Zimbabwe", code: "MASV28", Longitude: "", Latitude: "" },
{ suburb: "Glenlivet", code: "MASV29", Longitude: "", Latitude: "" },
{ suburb: "4 Brigade", code: "MASV30", Longitude: "", Latitude: "" },
{ suburb: "Happy Valley Farms", code: "MASV32", Longitude: "", Latitude: "" },
{ suburb: "Hillside", code: "MASV33", Longitude: "", Latitude: "" },
{ suburb: "Hotfield", code: "MASV34", Longitude: "", Latitude: "" },
{ suburb: "H.V.E. Farms", code: "MASV35", Longitude: "", Latitude: "" },
{ suburb: "H.V.E. section 5, 17", code: "MASV36", Longitude: "", Latitude: "" },
{ suburb: "H.V.E. Mill", code: "MASV37", Longitude: "", Latitude: "" },
{ suburb: "Jerera", code: "MASV38", Longitude: "", Latitude: "" },
{ suburb: "Jichidza", code: "MASV39", Longitude: "", Latitude: "" },
{ suburb: "King Mine", code: "MASV40", Longitude: "", Latitude: "" },
{ suburb: "Kyle schools", code: "MASV41", Longitude: "", Latitude: "" },
{ suburb: "Lennox Mine", code: "MASV42", Longitude: "", Latitude: "" },
{ suburb: "Levanga", code: "MASV43", Longitude: "", Latitude: "" },
{ suburb: "Madamombe", code: "MASV44", Longitude: "", Latitude: "" },
{ suburb: "Mahenye", code: "MASV45", Longitude: "", Latitude: "" },
{ suburb: "Majange", code: "MASV46", Longitude: "", Latitude: "" },
{ suburb: "Makuvaza", code: "MASV47", Longitude: "", Latitude: "" },
{ suburb: "Manhubvu", code: "MASV48", Longitude: "", Latitude: "" },
{ suburb: "Manzvire", code: "MASV49", Longitude: "", Latitude: "" },
{ suburb: "Mapanza", code: "MASV50", Longitude: "", Latitude: "" },
{ suburb: "Mapanzure", code: "MASV51", Longitude: "", Latitude: "" },
{ suburb: "Maranda", code: "MASV52", Longitude: "", Latitude: "" },
{ suburb: "Masapasi", code: "MASV53", Longitude: "", Latitude: "" },
{ suburb: "Mashoko", code: "MASV54", Longitude: "", Latitude: "" },
{ suburb: "Masvingo GMB", code: "MASV55", Longitude: "", Latitude: "" },
{ suburb: "Masvingo Tech", code: "MASV56", Longitude: "", Latitude: "" },
{ suburb: "Masvingo town", code: "MASV57", Longitude: "", Latitude: "" },
{ suburb: "Matsvange", code: "MASV58", Longitude: "", Latitude: "" },
{ suburb: "Mashava town & farms", code: "MASV59", Longitude: "", Latitude: "" },
{ suburb: "Malilangwe", code: "MASV60", Longitude: "", Latitude: "" },
{ suburb: "Mazungunye", code: "MASV61", Longitude: "", Latitude: "" },
{ suburb: "Mkwasine", code: "MASV62", Longitude: "", Latitude: "" },
{ suburb: "Mteri Pumps", code: "MASV63", Longitude: "", Latitude: "" },
{ suburb: "Mtikizizi", code: "MASV64", Longitude: "", Latitude: "" },
{ suburb: "Muchakata", code: "MASV65", Longitude: "", Latitude: "" },
{ suburb: "Muchibwa", code: "MASV66", Longitude: "", Latitude: "" },
{ suburb: "Mucheke D,E&F", code: "MASV67", Longitude: "", Latitude: "" },
{ suburb: "Mucheke Stadium", code: "MASV68", Longitude: "", Latitude: "" },
{ suburb: "Mutandahwe", code: "MASV69", Longitude: "", Latitude: "" },
{ suburb: "Mushanduri", code: "MASV70", Longitude: "", Latitude: "" },
{ suburb: "Muzondidya", code: "MASV71", Longitude: "", Latitude: "" },
{ suburb: "Mwenezi Estate", code: "MASV72", Longitude: "", Latitude: "" },
{ suburb: "Nandi", code: "MASV73", Longitude: "", Latitude: "" },
{ suburb: "National foods", code: "MASV74", Longitude: "", Latitude: "" },
{ suburb: "Nemanwa", code: "MASV75", Longitude: "", Latitude: "" },
{ suburb: "Nikipa", code: "MASV76", Longitude: "", Latitude: "" },
{ suburb: "Ngorima", code: "MASV77", Longitude: "", Latitude: "" },
{ suburb: "Northleigh", code: "MASV78", Longitude: "", Latitude: "" },
{ suburb: "Nyika", code: "MASV79", Longitude: "", Latitude: "" },
{ suburb: "Nyikavanhu", code: "MASV80", Longitude: "", Latitude: "" },
{ suburb: "Kyle Nat. Parks", code: "MASV81", Longitude: "", Latitude: "" },
{ suburb: "Ndanga", code: "MASV82", Longitude: "", Latitude: "" },
{ suburb: "Pris Research Station", code: "MASV83", Longitude: "", Latitude: "" },
{ suburb: "Rippling Waters", code: "MASV84", Longitude: "", Latitude: "" },
    { suburb: "Rhodene", code: "MASV85" , Longitude: "", Latitude: ""},
    { suburb: "Rujeko T/ship", code: "MASV87", Longitude: "", Latitude: "" },
    { suburb: "Runyararo West", code: "MASV88", Longitude: "", Latitude: "" },
    { suburb: "Rupike", code: "MASV89", Longitude: "", Latitude: "" },
    { suburb: "Rutenga", code: "MASV90", Longitude: "", Latitude: "" },
    { suburb: "Ruware", code: "MASV91", Longitude: "", Latitude: "" },
    { suburb: "Samba", code: "MASV92", Longitude: "", Latitude: "" },
    { suburb: "Save", code: "MASV93", Longitude: "", Latitude: "" },
    { suburb: "Sebanani", code: "MASV94", Longitude: "", Latitude: "" },
    { suburb: "Shonganiso", code: "MASV95", Longitude: "", Latitude: "" },
    { suburb: "Silveira Mission", code: "MASV96", Longitude: "", Latitude: "" },
    { suburb: "Sisk B/C", code: "MASV97", Longitude: "", Latitude: "" },
    { suburb: "Standard farm", code: "MASV98", Longitude: "", Latitude: "" },
    { suburb: "Steel Makers", code: "MASV99", Longitude: "", Latitude: "" },
    { suburb: "Stopover", code: "MASV100", Longitude: "", Latitude: "" },
    { suburb: "Target Kopje", code: "MASV101", Longitude: "", Latitude: "" },
    { suburb: "Temerira Mines", code: "MASV102", Longitude: "", Latitude: "" },
    { suburb: "Triangle", code: "MASV103", Longitude: "", Latitude: "" },
    { suburb: "Tshovani", code: "MASV104", Longitude: "", Latitude: "" },
    { suburb: "Tugwane", code: "MASV105", Longitude: "", Latitude: "" },
    { suburb: "Westview Industries", code: "MASV106", Longitude: "", Latitude: "" },
    { suburb: "Zaka", code: "MASV107", Longitude: "", Latitude: "" },
    { suburb: "ZSA", code: "MASV108", Longitude: "", Latitude: "" },
    { suburb: "Bangazani Dam", code: "MANI01", Longitude: "", Latitude: "" },
    { suburb: "Chipinge Hospital", code: "MANI02", Longitude: "", Latitude: "" },
    { suburb: "Chipinge Town", code: "MANI03", Longitude: "", Latitude: "" },
    { suburb: "Clearwater", code: "MANI04", Longitude: "", Latitude: "" },
    { suburb: "Far Fell Estate", code: "MANI05", Longitude: "", Latitude: "" },
    { suburb: "Green Valley", code: "MANI06", Longitude: "", Latitude: "" },
    { suburb: "Mt selinda border Chipinge post", code: "MANI07", Longitude: "", Latitude: "" },
    { suburb: "Ngungunyana forest", code: "MANI08", Longitude: "", Latitude: "" },
    { suburb: "Smalldell", code: "MANI09", Longitude: "", Latitude: "" },
    { suburb: "Zona Estate", code: "MANI10", Longitude: "", Latitude: "" },
    { suburb: "ZNA", code: "MANI11", Longitude: "", Latitude: "" },
    { suburb: "Bikita", code: "MSABI01", Longitude: "", Latitude: "" },
    { suburb: "Birchenough Bridge", code: "MSABI02", Longitude: "", Latitude: "" },
    { suburb: "Bonda Irrigation", code: "MSABI03", Longitude: "", Latitude: "" },
    { suburb: "Buhera", code: "MSABI04", Longitude: "", Latitude: "" },
    { suburb: "Nyanyadzi BC", code: "MSABI05", Longitude: "", Latitude: "" },
    { suburb: "Masapi Ranch", code: "MSABI06", Longitude: "", Latitude: "" },
    { suburb: "Maunganidze", code: "MSABI07", Longitude: "", Latitude: "" },
    { suburb: "Mutema", code: "MSABI08", Longitude: "", Latitude: "" },
    { suburb: "Mutema Irrigation", code: "MSABI09", Longitude: "", Latitude: "" },
    { suburb: "Rating", code: "MSABI10", Longitude: "", Latitude: "" },
    { suburb: "Tanganda", code: "MSABI11", Longitude: "", Latitude: "" },
    { suburb: "Tawona Irrigation", code: "MSABI12", Longitude: "", Latitude: "" },
    { suburb: "Buhera", code: "RUSA01", Longitude: "", Latitude: "" },
    { suburb: "Chikobvore BC", code: "RUSA02", Longitude: "", Latitude: "" },
    { suburb: "Chitenderano BC", code: "RUSA03", Longitude: "", Latitude: "" },
    { suburb: "Dakbreek Farm", code: "RUSA04", Longitude: "", Latitude: "" },
    { suburb: "Gandanzara", code: "RUSA05", Longitude: "", Latitude: "" },
    { suburb: "Leekil Clinic", code: "RUSA06", Longitude: "", Latitude: "" },
    { suburb: "Middle post farm", code: "RUSA07", Longitude: "", Latitude: "" },
    { suburb: "Murambinda", code: "RUSA08", Longitude: "", Latitude: "" },
    { suburb: "Nyazura Mission", code: "RUSA09", Longitude: "", Latitude: "" },
    { suburb: "Nyazura BC", code: "RUSA10", Longitude: "", Latitude: "" },
    { suburb: "Nyazura Prison", code: "RUSA11", Longitude: "", Latitude: "" },
    { suburb: "Rukweza BC", code: "RUSA12", Longitude: "", Latitude: "" },
    { suburb: "Rugoyi BC", code: "RUSA13", Longitude: "", Latitude: "" },
    { suburb: "St Kilen", code: "RUSA14", Longitude: "", Latitude: "" },
    { suburb: "Anderson school", code: "RUSA15", Longitude: "", Latitude: "" },
    { suburb: "3-2 Batallion", code: "RUSA16", Longitude: "", Latitude: "" },
    { suburb: "Dorowa Mine", code: "RUSA17", Longitude: "", Latitude: "" },
    { suburb: "Harrisonvale Farm", code: "RUSA18", Longitude: "", Latitude: "" },
    { suburb: "Mabvazuva", code: "RUSA19", Longitude: "", Latitude: "" },
    { suburb: "Magamba", code: "RUSA20", Longitude: "", Latitude: "" },
    { suburb: "Masvosva BC", code: "RUSA21", Longitude: "", Latitude: "" },
    { suburb: "Matsika BC", code: "RUSA22", Longitude: "", Latitude: "" },
    { suburb: "Nhedziwa Clinic", code: "RUSA23", Longitude: "", Latitude: "" },
    { suburb: "Nyabadza BC", code: "RUSA24", Longitude: "", Latitude: "" },
    { suburb: "Nyahukwe Clinic", code: "RUSA25", Longitude: "", Latitude: "" },
    { suburb: "Tsanzaguru", code: "RUSA26", Longitude: "", Latitude: "" },
    { suburb: "St Faith School", code: "RUSA27", Longitude: "", Latitude: "" },
    { suburb: "Vhengere", code: "RUSA28", Longitude: "", Latitude: "" },
    { suburb: "Wakefield Estate", code: "RUSA29", Longitude: "", Latitude: "" },
    { suburb: "Whitgift", code: "RUSA30", Longitude: "", Latitude: "" },
    { suburb: "Yorkshire", code: "RUSA31", Longitude: "", Latitude: "" },
    { suburb: "Zambara VHF", code: "RUSA32", Longitude: "", Latitude: "" },
    { suburb: "Arda transau", code: "MUTA01", Longitude: "", Latitude: "" },
    { suburb: "Adams Barracks", code: "MUTA02", Longitude: "", Latitude: "" },
    { suburb: "Africa University", code: "MUTA03", Longitude: "", Latitude: "" },
    { suburb: "Bonda", code: "MUTA04", Longitude: "", Latitude: "" },
    { suburb: "Bordervale", code: "MUTA05", Longitude: "", Latitude: "" },
    { suburb: "Border Timbers (Nyakamete & Paulington)", code: "MUTA06", Longitude: "", Latitude: "" },
    { suburb: "Burma Valley", code: "MUTA07", Longitude: "", Latitude: "" },
    { suburb: "Mutare Boys High", code: "MUTA08", Longitude: "", Latitude: "" },
    { suburb: "CABS", code: "MUTA09", Longitude: "", Latitude: "" },
    { suburb: "Civic Centre", code: "MUTA10", Longitude: "", Latitude: "" },
    { suburb: "Chikanga 1, 2 & 3", code: "MUTA11", Longitude: "", Latitude: "" },
    { suburb: "Chisamba singles", code: "MUTA12", Longitude: "", Latitude: "" },
    { suburb: "Chigodora", code: "MUTA13", Longitude: "", Latitude: "" },
    { suburb: "Chitakatira", code: "MUTA14", Longitude: "", Latitude: "" },
    { suburb: "Chancellor", code: "MUTA15", Longitude: "", Latitude: "" },
    { suburb: "Chinota", code: "MUTA16", Longitude: "", Latitude: "" },
    { suburb: "Devonshire", code: "MUTA17", Longitude: "", Latitude: "" },
    { suburb: "Dangamvura", code: "MUTA18", Longitude: "", Latitude: "" },
    { suburb: "Darlington", code: "MUTA19", Longitude: "", Latitude: "" },
    { suburb: "Dominic high", code: "MUTA20", Longitude: "", Latitude: "" },
    { suburb: "DMB", code: "MUTA21", Longitude: "", Latitude: "" },
    { suburb: "Domborutinha", code: "MUTA22", Longitude: "", Latitude: "" },
    { suburb: "Downtown", code: "MUTA23", Longitude: "", Latitude: "" },
    { suburb: "Dangare (new & old)", code: "MUTA24", Longitude: "", Latitude: "" },
    { suburb: "Dangamvura Eastern District Engineers", code: "MUTA25", Longitude: "", Latitude: "" },
    { suburb: "Eastern Gateway", code: "MUTA26", Longitude: "", Latitude: "" },
    { suburb: "Forbes Border post", code: "MUTA27", Longitude: "", Latitude: "" },
   
    { suburb: "Green Market", code: "MUTA28", Longitude: "", Latitude: "" },
    { suburb: "GMB", code: "MUTA29", Longitude: "", Latitude: "" },
    { suburb: "Greenside", code: "MUTA30", Longitude: "", Latitude: "" },
    { suburb: "Florida", code: "MUTA31" , Longitude: "", Latitude: ""},
    { suburb: "Fairbridge", code: "MUTA32", Longitude: "", Latitude: "" },
    { suburb: "3 Brigade", code: "MUTA33", Longitude: "", Latitude: "" },
    { suburb: "Hobhouse", code: "MUTA34", Longitude: "", Latitude: "" },
    { suburb: "Holiday Inn", code: "MUTA35", Longitude: "", Latitude: "" },
    { suburb: "Honde Valley", code: "MUTA36", Longitude: "", Latitude: "" },
    { suburb: "Hughes Eng", code: "MUTA37", Longitude: "", Latitude: "" },
    { suburb: "Marange", code: "MUTA38", Longitude: "", Latitude: "" },
    { suburb: "Mapembe", code: "MUTA39", Longitude: "", Latitude: "" },
    { suburb: "Mazhambe", code: "MUTA40", Longitude: "", Latitude: "" },
    { suburb: "Matondo", code: "MUTA41", Longitude: "", Latitude: "" },
    { suburb: "Main camp ZRP", code: "MUTA42", Longitude: "", Latitude: "" },
    { suburb: "Morningside", code: "MUTA43", Longitude: "", Latitude: "" },
    { suburb: "Murambi", code: "MUTA44", Longitude: "", Latitude: "" },
    { suburb: "Mutare CBD", code: "MUTA45", Longitude: "", Latitude: "" },
    { suburb: "Municipal Brewery", code: "MUTA46", Longitude: "", Latitude: "" },
    { suburb: "Mutare Technical college", code: "MUTA47", Longitude: "", Latitude: "" },
    { suburb: "NRZ station", code: "MUTA48", Longitude: "", Latitude: "" },
    { suburb: "Nyausunzwi", code: "MUTA49", Longitude: "", Latitude: "" },
    { suburb: "Old Mutare", code: "MUTA50", Longitude: "", Latitude: "" },
    { suburb: "Penhalonga", code: "MUTA51", Longitude: "", Latitude: "" },
    { suburb: "Palmerstone", code: "MUTA52", Longitude: "", Latitude: "" },
    { suburb: "Piki", code: "MUTA53", Longitude: "", Latitude: "" },
    { suburb: "Quest Motors", code: "MUTA54", Longitude: "", Latitude: "" },
    { suburb: "Odzani", code: "MUTA55", Longitude: "", Latitude: "" },
    { suburb: "Odzi", code: "MUTA56", Longitude: "", Latitude: "" },
    { suburb: "Osborn Dam", code: "MUTA57", Longitude: "", Latitude: "" },
    { suburb: "Redwing", code: "MUTA58", Longitude: "", Latitude: "" },
    { suburb: "Rodel", code: "MUTA59", Longitude: "", Latitude: "" },
    { suburb: "Industrial Area (Mutare)", code: "MUTA60", Longitude: "", Latitude: "" },
    { suburb: "Sakubva", code: "MUTA61", Longitude: "", Latitude: "" },
    { suburb: "St. Josephs", code: "MUTA62", Longitude: "", Latitude: "" },
    { suburb: "Stapleford", code: "MUTA63", Longitude: "", Latitude: "" },
    { suburb: "Stewart & Lloyds", code: "MUTA64", Longitude: "", Latitude: "" },
    { suburb: "Shamhu", code: "MUTA65", Longitude: "", Latitude: "" },
    { suburb: "Tanganda", code: "MUTA66", Longitude: "", Latitude: "" },
    { suburb: "Toronto", code: "MUTA67", Longitude: "", Latitude: "" },
    { suburb: "Troutbek", code: "MUTA68", Longitude: "", Latitude: "" },
    { suburb: "Vumba", code: "MUTA69", Longitude: "", Latitude: "" },
    { suburb: "Warham", code: "MUTA70", Longitude: "", Latitude: "" },
    { suburb: "Watsomba", code: "MUTA71", Longitude: "", Latitude: "" },
    { suburb: "Weirmouth", code: "MUTA72", Longitude: "", Latitude: "" },
    { suburb: "Westlea", code: "MUTA73" , Longitude: "", Latitude: ""},
    { suburb: "Yeovil", code: "MUTA74" , Longitude: "", Latitude: ""},
    { suburb: "Zimboard", code: "MUTA75", Longitude: "", Latitude: "" },
    { suburb: "Zimunya", code: "MUTA76" , Longitude: "", Latitude: ""},
    { suburb: "Zororo (new & old)", code: "MUTA77" , Longitude: "", Latitude: ""},
    { suburb: "22 miles", code: "MUTA78" , Longitude: "", Latitude: ""},
    { suburb: "ZRP Mutare rural camp", code: "MUTA79", Longitude: "", Latitude: ""},
    { suburb: "Avila", code: "NYAN01", Longitude: "", Latitude: "" },
    { suburb: "Bende", code: "NYAN02", Longitude: "", Latitude: "" },
    { suburb: "Bonda", code: "NYAN03", Longitude: "", Latitude: "" },
    { suburb: "Juliusdale", code: "NYAN04" , Longitude: "", Latitude: ""},
    { suburb: "Church house", code: "NYAN05" , Longitude: "", Latitude: ""},
    { suburb: "Honde Valley", code: "NYAN06", Longitude: "", Latitude: "" },
    { suburb: "Kairezi", code: "NYAN07", Longitude: "", Latitude: "" },
    { suburb: "Kanyimo", code: "NYAN08", Longitude: "", Latitude: "" },
    { suburb: "Kunyu", code: "NYAN09" , Longitude: "", Latitude: ""},
    { suburb: "Kwaraguza", code: "NYAN10" , Longitude: "", Latitude: ""},
    { suburb: "Little Conmara", code: "NYAN11", Longitude: "", Latitude: "" },
    { suburb: "Mangondoza", code: "NYAN12" , Longitude: "", Latitude: ""},
    { suburb: "Matema", code: "NYAN13" , Longitude: "", Latitude: ""},
    { suburb: "Nyamaropa", code: "NYAN14", Longitude: "", Latitude: "" },
    { suburb: "Nyamhuka 1 & 2", code: "NYAN15" , Longitude: "", Latitude: ""},
    { suburb: "Nyanga Downs", code: "NYAN16" , Longitude: "", Latitude: ""},
    { suburb: "Nyanga Gvt Area", code: "NYAN17" , Longitude: "", Latitude: ""},
    { suburb: "Nyanga town", code: "NYAN18" , Longitude: "", Latitude: ""},
    { suburb: "Nyanga National Park", code: "NYAN19" , Longitude: "", Latitude: ""},
    { suburb: "Nyangui", code: "NYAN20", Longitude: "", Latitude: "" },
    { suburb: "Nyarumvurwe", code: "NYAN21" , Longitude: "", Latitude: ""},
    { suburb: "Nyatate", code: "NYAN22", Longitude: "", Latitude: "" },
    { suburb: "Nyautare", code: "NYAN23" , Longitude: "", Latitude: ""},
    { suburb: "Rodel", code: "NYAN24" , Longitude: "", Latitude: ""},
    { suburb: "Regina", code: "NYAN25" , Longitude: "", Latitude: ""},
    { suburb: "Rukotso", code: "NYAN26" , Longitude: "", Latitude: ""},
    { suburb: "Ruwangwe", code: "NYAN27" , Longitude: "", Latitude: ""},
    { suburb: "Sedze", code: "NYAN28" , Longitude: "", Latitude: ""},
    { suburb: "St Marrys", code: "NYAN29", Longitude: "", Latitude: "" },
    { suburb: "Tombo", code: "NYAN30" , Longitude: "", Latitude: ""},
    { suburb: "Transmedia", code: "NYAN31", Longitude: "", Latitude: "" },
    { suburb: "Troutbek", code: "NYAN32", Longitude: "", Latitude: "" },
    { suburb: "Tsatse", code: "NYAN33", Longitude: "", Latitude: "" },
    { suburb: "Watsomba", code: "NYAN34", Longitude: "", Latitude: "" },
    { suburb: "Valley Road", code: "NYAN35" , Longitude: "", Latitude: ""},
  { suburb: "Chinotimba", code: "VICF01", Longitude: "", Latitude: "" },
  { suburb: "Mkhosana", code: "VICF02" , Longitude: "", Latitude: ""},
  { suburb: "Industrial Area", code: "VICF03", Longitude: "", Latitude: "" },
  { suburb: "CBD", code: "VICF04", Longitude: "", Latitude: "" },
  { suburb: "Low Density", code: "VICF05" , Longitude: "", Latitude: ""},
  { suburb: "Baobab", code: "VICF06" , Longitude: "", Latitude: ""},
  { suburb: "Aero Township", code: "VICF07" , Longitude: "", Latitude: ""},
  { suburb: "Batoka", code: "VICF08" , Longitude: "", Latitude: ""},
  { suburb: "Zambezi Park", code: "VICF09", Longitude: "", Latitude: "" },
  { suburb: "Lodge Area", code: "VICF10", Longitude: "", Latitude: "" },
  { suburb: "Cooksey", code: "CHIN01", Longitude: "", Latitude: "" },
    { suburb: "Chikonohono", code: "CHIN02", Longitude: "", Latitude: "" },
    { suburb: "Cold Stream", code: "CHIN03", Longitude: "", Latitude: "" },
    { suburb: "Mapako", code: "CHIN04" , Longitude: "", Latitude: ""},
    { suburb: "White City", code: "CHIN05" , Longitude: "", Latitude: ""},
    { suburb: "Cherutombo", code: "CHIN06", Longitude: "", Latitude: "" },
    { suburb: "Shingiro", code: "CHIN07", Longitude: "", Latitude: "" },
    { suburb: "Chikangwe", code: "CHIN08" , Longitude: "", Latitude: ""},
    { suburb: "Hunyani", code: "CHIN09", Longitude: "", Latitude: "" },
    { suburb: "Chinhoyi University", code: "CHIN10", Longitude: "", Latitude: "" },
    { suburb: "Chimoyo", code: "MUTO01" , Longitude: "", Latitude: ""},
    { suburb: "Nyamuzuwe", code: "MUTO02" , Longitude: "", Latitude: ""},
    { suburb: "Mutoko Centre", code: "MUTO03" , Longitude: "", Latitude: ""},
    { suburb: "Kawere", code: "MUTO04", Longitude: "", Latitude: "" },
    { suburb: "Mbudzi", code: "MUTO05" , Longitude: "", Latitude: ""},
    { suburb: "Chingamuka", code: "MUTO06", Longitude: "", Latitude: "" },
    { suburb: "Musinami", code: "MUTO07", Longitude: "", Latitude: "" },
    { suburb: "Nyadire", code: "MUTO08", Longitude: "", Latitude: "" },
    { suburb: "Chitukuko", code: "MUTO09", Longitude: "", Latitude: "" },
    { suburb: "Munyai", code: "MUTO10" , Longitude: "", Latitude: ""},
    { suburb: "Amaveni", code: "KWEK01", Longitude: "", Latitude: "" },
    { suburb: "City Centre", code: "KWEK02", Longitude: "", Latitude: "" },
    { suburb: "Goldridge", code: "KWEK03", Longitude: "", Latitude: "" },
    { suburb: "Mbizo", code: "KWEK04" , Longitude: "", Latitude: ""},
    { suburb: "Redcliff", code: "KWEK05", Longitude: "", Latitude: "" },
    { suburb: "Msasa Park", code: "KWEK06" , Longitude: "", Latitude: ""},
    { suburb: "Newtown", code: "KWEK07" , Longitude: "", Latitude: ""},
    { suburb: "Southwood", code: "KWEK08", Longitude: "", Latitude: "" },
    { suburb: "Harrisville", code: "KWEK09", Longitude: "", Latitude: "" },
    { suburb: "Rutendo", code: "KWEK10", Longitude: "", Latitude: "" }

];

const mergeSuburbs = (suburbs) => {
  const mergedSuburbs = {};
  suburbs.forEach((suburbObj) => {
    if (!mergedSuburbs[suburbObj.code]) {
      mergedSuburbs[suburbObj.code] = suburbObj.suburb;
    } else {
      mergedSuburbs[suburbObj.code] += `, ${suburbObj.suburb}`;
    }
  });
  return Object.entries(mergedSuburbs).map(([code, suburb]) => ({ code, suburb }));
};
const seedSuburbs = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true
    });

    console.log('MongoDB connected');
    
    // Remove existing suburbs
    await Suburb.deleteMany({});
    console.log('Existing suburbs removed');

    const mergedSuburbs = mergeSuburbs(suburbs);
    
    // Filter out duplicate suburbs
    const uniqueSuburbs = {};
    mergedSuburbs.forEach(suburb => {
      if (!uniqueSuburbs[suburb.suburb]) {
        uniqueSuburbs[suburb.suburb] = suburb;
      }
    });
    const suburbsToInsert = Object.values(uniqueSuburbs);

    // Ensure each suburb object has a valid code before inserting
    const validSuburbs = suburbsToInsert.filter(suburb => suburb.code);

    // Insert unique and valid suburbs
    await Suburb.insertMany(validSuburbs);
    console.log('Suburbs inserted');

    mongoose.disconnect();
    console.log('MongoDB disconnected');
  } catch (err) {
    console.error('Error seeding suburbs:', err);
    mongoose.disconnect();
  }
};

module.exports = seedSuburbs;


seedSuburbs();
