// suburbs.js
const suburbs = [
    // HARARE DISTRICT
    { suburb: "Avondale", code: "HAR01" },
    { suburb: "Borrowdale", code: "HAR02" },
    { suburb: "Eastlea", code: "HAR03" },
    { suburb: "Highlands", code: "HAR04" },
    { suburb: "Mbare", code: "HAR05" },
    { suburb: "Mt. Pleasant", code: "HAR06" },
    { suburb: "Waterfalls", code: "HAR07" },
    { suburb: "Westgate", code: "HAR08" },
    { suburb: "Greendale", code: "HAR09" },
    { suburb: "Kuwadzana", code: "HAR10" },
    // BULAWAYO DISTRICT
    { suburb: "Barbourfields", code: "BULA01" },
    { suburb: "Bellevue", code: "BULA02" },
    { suburb: "City Centre", code: "BULA03" },
    { suburb: "Emakhandeni", code: "BULA04" },
    { suburb: "Famona", code: "BULA05" },
    { suburb: "Hillside", code: "BULA06" },
    { suburb: "Mahatshula", code: "BULA07" },
    { suburb: "Nkulumane", code: "BULA08" },
    { suburb: "North End", code: "BULA09" },
    { suburb: "Pelandaba", code: "BULA10" },
    // GWERU DISTRICT
    { suburb: "Ascot", code: "GWER01" },
    { suburb: "City Centre", code: "GWER02" },
    { suburb: "Lundi Park", code: "GWER03" },
    { suburb: "Mkoba", code: "GWER04" },
    { suburb: "Southdowns", code: "GWER05" },
    { suburb: "Ridgemont", code: "GWER06" },
    { suburb: "Kopje", code: "GWER07" },
    { suburb: "Ivene", code: "GWER08" },
    { suburb: "Mtapa", code: "GWER09" },
    { suburb: "Senga", code: "GWER10" },
    // KWEKWE DISTRICT
    { suburb: "Amaveni", code: "KWEK01" },
    { suburb: "City Centre", code: "KWEK02" },
    { suburb: "Goldridge", code: "KWEK03" },
    { suburb: "Mbizo", code: "KWEK04" },
    { suburb: "Redcliff", code: "KWEK05" },
    { suburb: "Msasa Park", code: "KWEK06" },
    { suburb: "Newtown", code: "KWEK07" },
    { suburb: "Southwood", code: "KWEK08" },
    { suburb: "Harrisville", code: "KWEK09" },
    { suburb: "Rutendo", code: "KWEK10" },
    // MUTOKO DISTRICT
    { suburb: "Chimoyo", code: "MUTO01" },
    { suburb: "Nyamuzuwe", code: "MUTO02" },
    { suburb: "Mutoko Centre", code: "MUTO03" },
    { suburb: "Kawere", code: "MUTO04" },
    { suburb: "Mbudzi", code: "MUTO05" },
    { suburb: "Chingamuka", code: "MUTO06" },
    { suburb: "Musinami", code: "MUTO07" },
    { suburb: "Nyadire", code: "MUTO08" },
    { suburb: "Chitukuko", code: "MUTO09" },
    { suburb: "Munyai", code: "MUTO10" },
    // CHINHOYI DISTRICT
    { suburb: "Cooksey", code: "CHIN01" },
    { suburb: "Chikonohono", code: "CHIN02" },
    { suburb: "Cold Stream", code: "CHIN03" },
    { suburb: "Mapako", code: "CHIN04" },
    { suburb: "White City", code: "CHIN05" },
    { suburb: "Cherutombo", code: "CHIN06" },
    { suburb: "Shingiro", code: "CHIN07" },
    { suburb: "Chikangwe", code: "CHIN08" },
    { suburb: "Hunyani", code: "CHIN09" },
    { suburb: "Chinhoyi University", code: "CHIN10" },
    // VICTORIA FALLS DISTRICT
    { suburb: "Chinotimba", code: "VICF01" },
    { suburb: "Mkhosana", code: "VICF02" },
    { suburb: "Industrial Area", code: "VICF03" },
    { suburb: "CBD", code: "VICF04" },
    { suburb: "Low Density", code: "VICF05" },
    { suburb: "Baobab", code: "VICF06" },
    { suburb: "Aero Township", code: "VICF07" },
    { suburb: "Batoka", code: "VICF08" },
    { suburb: "Zambezi Park", code: "VICF09" },
    { suburb: "Lodge Area", code: "VICF10" }
];

module.exports = suburbs;
